spring.application.name=smart-contact-manager

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smart_contact_manager
spring.datasource.username=root
spring.datasource.password=8432513435Ritesh

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true